version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis  # Use the Redis service name
      - REDIS_PORT=6379
      - DATABASE_URL=sqlite:///data.db  # Replace with your actual DB URL if needed
      - JWT_SECRET_KEY=your-secret-key  # Replace with your secret key
    depends_on:
      - redis  # Ensure Redis starts before Flask
    volumes:
      - .:/app  # Optional: Mount current directory to container for dev

  redis:
    image: redis:alpine  # Use a lightweight Redis image
    ports:
      - "6379:6379"  # Map Redis port 6379 to host
